export default {
  "login": "HoseaCodes",
  "id": 66652422,
  "node_id": "MDQ6VXNlcjY2NjUyNDIy",
  "avatar_url": "https://avatars2.githubusercontent.com/u/66652422?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/HoseaCodes",
  "html_url": "https://github.com/HoseaCodes",
  "followers_url": "https://api.github.com/users/HoseaCodes/followers",
  "following_url": "https://api.github.com/users/HoseaCodes/following{/other_user}",
  "gists_url": "https://api.github.com/users/HoseaCodes/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/HoseaCodes/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/HoseaCodes/subscriptions",
  "organizations_url": "https://api.github.com/users/HoseaCodes/orgs",
  "repos_url": "https://api.github.com/users/HoseaCodes/repos",
  "events_url": "https://api.github.com/users/HoseaCodes/events{/privacy}",
  "received_events_url": "https://api.github.com/users/HoseaCodes/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Dominique Hosea",
  "company": null,
  "blog": "https://www.linkedin.com/in/dominique-hosea/",
  "location": "Houston, TX",
  "email": null,
  "hireable": null,
  "bio": "\r\n    Hello my name is Dominique and I am an aspiring software engineer specializing in MERN stack. I have a strong passion for innovation and creation. \r\n",
  "twitter_username": "DominiqueRHosea",
  "public_repos": 12,
  "public_gists": 0,
  "followers": 1,
  "following": 1,
  "created_at": "2020-06-09T00:37:57Z",
  "updated_at": "2020-08-21T18:07:27Z"
};
